name: Deploy to AWS

on:
  push:
    branches:
      - main
      - javin/deployment

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          IMAGE_PREFIX: "${{ steps.login-ecr.outputs.registry }}/lastminprep/"
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker compose build
          docker compose push
