name: CI

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    types: [opened, synchronize]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # We un-hoist packages to ensure that each package has the necessary
      # dependencies and do not rely implicitly on dependencies from other packages.
      - name: Un-hoist packages
        run: |
          sed -i 's/node-linker=hoisted/node-linker=isolated/g' .npmrc

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

  lint:
    name: Type Check & Lint
    needs:
      - install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Un-hoist packages
        run: |
          sed -i 's/node-linker=hoisted/node-linker=isolated/g' .npmrc

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type checking
        run: pnpm type-check

      - name: Run linting
        run: pnpm lint
